#!/usr/bin/env node
const fs = require('fs');

function toTitleCase(str) {
  return str.replace(
    /\w\S*/g,
    function(txt) {
      return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    }
  );
}

const componentName = process.argv[2];

const dashCase = /[a-z\-]+$/;

if(!componentName.match(dashCase)) {
  console.error("Format Error: Remeber to use dash case for the name like this `component-name`");
  process.exit(1);
}

console.log("Removing files...");


const configContent = fs.readFileSync('./src/config/scripts/index.js').toString().split("\n");
const removedLine = `import '../../components/${componentName}/${componentName}';`;
const newConfigContent = configContent.filter(line => line !== removedLine).join("\n");

fs.writeFile('./src/config/scripts/index.js', newConfigContent, function (err) {
  if (err) return err;
});

const dir = `./src/components/${componentName}`;

fs.rmdir(dir, { recursive: true }, (err) => {
  if (err) {
      throw err;
  }

  console.log(`${componentName} was deleted!`);
});
